# spatial_environment.yml
name: spatialanalysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy<2.0 
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - scanpy
  - anndata
  - squidpy
  - scipy
  - pip
  - pip:
    - scimap
    - git+https://github.com/semenovlab/SpatialCells.git